### ISSUE TITLE
This method should be const qualified since it does not modify the class

### ISSUE THREAD

**Issue by deanagan** [Hydroleks/cppPatternPractice#1]
https://github.com/Hydroleks/cppPatternPractice/blob/4c59d9fdba4fe571dd1b352a2a62eee00783c54c/Patterns/AbstractFactory/RestaurantBase.h#L12

**Comment by leksandar-stojanovic** [comment]
Cheers, I have applied the consts for the Abstract factory, but did not apply it to other places. Probably should do that.
